### ISSUE TITLE
Control K overriden by Vcs.ToggleAmendCommitMode

### ISSUE THREAD

**Issue by charjr** [strindberg/emacsj#59] opened 2024-06-25 13:39 UTC
[Looking at the Emacs keymap](https://github.com/JetBrains/intellij-community/blob/2c8d9f7ca1fc54419ff84586d4842ed7f2b76317/platform/platform-resources/src/keymaps/Emacs.xml#L324C3-L324C43), I can see the following disabled command:

```xml
<action id="Vcs.ToggleAmendCommitMode"/>
```

And the EmacsJ keymap has

```xml
<keymap name="EmacsJ" parent="Emacs" version="1.2.0">
```

Despite this, pressing `control + k` seems to perform `Vcs.ToggleAmendCommitMode`.

I don't know why it is not inheriting the behaviour properly. 

But perhaps disabling that action explicitly in the keymap would solve it?

**Comment by strindberg** [comment] 2024-07-02 06:12
Thank you for the report.

I have not been able to reproduce this: `control + k`  kills the line both with the Emacs and the EmacsJ keymaps in all IntelliJ versions that I have tested. Is it in a particular dialog or editor that you see this problem?

**Comment by charjr** [comment] 2024-07-02 17:11
Using PHPStorm when set to the EmacsJ keymap.

I do not experience it using the Emacs keymap.

I am using the new UI, and I am running it on Linux, downloaded as a Snap.

It may well be an issue on my end as your keymap literally inherits from Emacs so I don't see anything wrong with the code.

**Comment by strindberg** [comment] 2024-07-11 07:02
Try as I might, I cannot reproduce this problem, and to me the code seems correct. I will close this issue, bu feel free to open a new issue if you can find a way to reproduce it. I have seen other problems with IntelliJ shadowing plugin shortcuts, but I don't think this is the same problem.

I assume you know how to fix you specific problem by un-assigning the shortcut to `Vcs.ToggleAmendCommitMode`?

**Closed** 2024-07-11 07:02 UTC
